[[plugins]]
repo = 'https://github.com/vim-denops/denops.vim'

[[plugins]]
repo = 'https://github.com/joshdick/onedark.vim'

[[plugins]]
repo = 'https://github.com/folke/tokyonight.nvim'

[[plugins]]
repo = 'https://github.com/vim-airline/vim-airline'

[[plugins]]
repo = 'https://github.com/vim-airline/vim-airline-themes'

[[plugins]]
repo = 'https://github.com/github/copilot.vim'

[[plugins]]
repo = 'https://github.com/tpope/vim-surround'

[[plugins]]
repo = 'https://github.com/tpope/vim-commentary'

