[[plugins]]
repo = 'vim-denops/denops.vim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'catppuccin/nvim'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'

[[plugins]]
repo = 'kepano/flexoki-neovim'

[[plugins]]
repo = 'doums/darcula'

[[plugins]]
repo = 'tomasiser/vim-code-dark'

[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'

