# Basic plugins
[[plugins]]
repo = 'neovim/nvim-lspconfig'

[[plugins]]
repo = 'github/copilot.vim'

[[plugins]]
repo = 'vim-denops/denops.vim'

# Colorschemes plugins
[[plugins]]
repo = 'catppuccin/nvim'

[[plugins]]
repo = 'doums/darcula'

[[plugins]]
repo = 'EdenEast/nightfox.nvim'

[[plugins]]
repo = 'ellisonleao/gruvbox.nvim'

[[plugins]]
repo = 'folke/tokyonight.nvim'

[[plugins]]
repo = 'joshdick/onedark.vim'

[[plugins]]
repo = 'kepano/flexoki-neovim'

[[plugins]]
repo = 'rebelot/kanagawa.nvim'

[[plugins]]
repo = 'tomasiser/vim-code-dark'

# UI plugins
[[plugins]]
repo = 'vim-airline/vim-airline'

[[plugins]]
repo = 'vim-airline/vim-airline-themes'

# Operations plugins
[[plugins]]
repo = 'tpope/vim-surround'

[[plugins]]
repo = 'tpope/vim-commentary'

# Extensions plugins
[[plugins]]
repo = 'tpope/vim-dadbod'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-ui'

[[plugins]]
repo = 'kristijanhusak/vim-dadbod-completion'

