[[plugins]]
repo = 'https://github.com/Shougo/ddc.vim'

[[plugins]]
repo = 'https://github.com/Shougo/pum.vim'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-ui-pum'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-around'

[[plugins]]
repo = 'https://github.com/LumaKernel/ddc-source-file'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-source-lsp'

[[plugins]]
repo = 'https://github.com/neovim/nvim-lspconfig'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-matcher_head'

[[plugins]]
repo = 'https://github.com/Shougo/ddc-sorter_rank'

